"""initial schema

Revision ID: 7588a5407449
Revises: 
Create Date: 2026-09-09 23:08:07.946485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7588a5407449'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_ml', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_slug'), 'districts', ['slug'], unique=True)
    op.create_table('otp_codes',
    sa.Column('target', sa.String(length=320), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', name='otp_channel'), nullable=False),
    sa.Column('purpose', sa.Enum('LOGIN', 'VERIFY_EMAIL', 'VERIFY_PHONE', name='otp_purpose'), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_target_purpose', 'otp_codes', ['target', 'purpose'], unique=False)
    op.create_table('plans',
    sa.Column('code', sa.Enum('HELPER_MONTHLY', 'HIRER_MONTHLY', name='plan_code'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('razorpay_plan_id', sa.String(length=64), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('interval_unit', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True)
    op.create_table('services',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_ml', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    op.create_table('skills',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_ml', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'HELPER', 'HIRER', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='user_status'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name='ck_users_email_or_phone'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('webhook_events',
    sa.Column('razorpay_event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_razorpay_event_id'), 'webhook_events', ['razorpay_event_id'], unique=True)
    op.create_table('admin_actions',
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'APPLE', 'EMAIL', 'PHONE', name='auth_provider'), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_identity_provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('ID_PROOF', 'ADDRESS_PROOF', 'POLICE_VERIFICATION', 'PHOTO', name='document_kind'), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='document_status'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('hire_requests',
    sa.Column('hirer_id', sa.UUID(), nullable=False),
    sa.Column('helper_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'WITHDRAWN', 'COMPLETED', name='hire_request_status'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['helper_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hirer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hire_helper_status', 'hire_requests', ['helper_id', 'status'], unique=False)
    op.create_index('ix_hire_hirer_status', 'hire_requests', ['hirer_id', 'status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'AUTHENTICATED', 'ACTIVE', 'PENDING', 'HALTED', 'CANCELLED', 'COMPLETED', 'EXPIRED', name='subscription_status'), nullable=False),
    sa.Column('current_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('charge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_razorpay_subscription_id'), 'subscriptions', ['razorpay_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('towns',
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_ml', sa.String(length=120), nullable=False),
    sa.Column('is_major', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_towns_district_id'), 'towns', ['district_id'], unique=False)
    op.create_index(op.f('ix_towns_slug'), 'towns', ['slug'], unique=False)
    op.create_table('helper_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('headline', sa.String(length=160), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('wage_monthly_min', sa.Integer(), nullable=False),
    sa.Column('wage_monthly_max', sa.Integer(), nullable=False),
    sa.Column('shifts', sa.ARRAY(sa.Enum('MORNING', 'AFTERNOON', 'EVENING', 'FULL_DAY', name='shift')), nullable=False),
    sa.Column('hours_per_day', sa.Integer(), nullable=False),
    sa.Column('willing_to_live_in', sa.Boolean(), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('town_id', sa.UUID(), nullable=True),
    sa.Column('landmark', sa.String(length=160), nullable=False),
    sa.Column('photo_key', sa.String(length=255), nullable=True),
    sa.Column('photo_cutout_key', sa.String(length=255), nullable=True),
    sa.Column('cutout_status', sa.Enum('PENDING', 'DONE', 'FAILED', name='cutout_status'), nullable=False),
    sa.Column('id_verification_status', sa.Enum('NONE', 'PENDING', 'VERIFIED', 'REJECTED', name='verification_status'), nullable=False),
    sa.Column('police_verification_status', sa.Enum('NONE', 'PENDING', 'VERIFIED', 'REJECTED', name='verification_status'), nullable=False),
    sa.Column('is_listed', sa.Boolean(), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hours_per_day BETWEEN 1 AND 16', name='ck_helper_hours_per_day'),
    sa.CheckConstraint('wage_monthly_max >= wage_monthly_min', name='ck_helper_wage_range'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['town_id'], ['towns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_helper_listed_service', 'helper_profiles', ['is_listed', 'service_id'], unique=False)
    op.create_index('ix_helper_location', 'helper_profiles', ['district_id', 'town_id'], unique=False)
    op.create_index(op.f('ix_helper_profiles_is_listed'), 'helper_profiles', ['is_listed'], unique=False)
    op.create_index(op.f('ix_helper_profiles_service_id'), 'helper_profiles', ['service_id'], unique=False)
    op.create_index('ix_helper_wage', 'helper_profiles', ['wage_monthly_min', 'wage_monthly_max'], unique=False)
    op.create_table('hirer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('town_id', sa.UUID(), nullable=True),
    sa.Column('landmark', sa.String(length=160), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['town_id'], ['towns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('payments',
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_table('reviews',
    sa.Column('hire_request_id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('ratee_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('HIRER_TO_HELPER', 'HELPER_TO_HIRER', name='review_direction'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['hire_request_id'], ['hire_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ratee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hire_request_id', 'direction', name='uq_review_once_per_side')
    )
    op.create_index(op.f('ix_reviews_ratee_id'), 'reviews', ['ratee_id'], unique=False)
    op.create_table('helper_skills',
    sa.Column('helper_profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['helper_profile_id'], ['helper_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('helper_profile_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helper_skills')
    op.drop_index(op.f('ix_reviews_ratee_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('hirer_profiles')
    op.drop_index('ix_helper_wage', table_name='helper_profiles')
    op.drop_index(op.f('ix_helper_profiles_service_id'), table_name='helper_profiles')
    op.drop_index(op.f('ix_helper_profiles_is_listed'), table_name='helper_profiles')
    op.drop_index('ix_helper_location', table_name='helper_profiles')
    op.drop_index('ix_helper_listed_service', table_name='helper_profiles')
    op.drop_table('helper_profiles')
    op.drop_index(op.f('ix_towns_slug'), table_name='towns')
    op.drop_index(op.f('ix_towns_district_id'), table_name='towns')
    op.drop_table('towns')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_razorpay_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_hire_hirer_status', table_name='hire_requests')
    op.drop_index('ix_hire_helper_status', table_name='hire_requests')
    op.drop_table('hire_requests')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_table('admin_actions')
    op.drop_index(op.f('ix_webhook_events_razorpay_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.drop_table('plans')
    op.drop_index('ix_otp_target_purpose', table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_districts_slug'), table_name='districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
