"""round 2 messaging categories moderation prefs

Revision ID: 8d3248dcc984
Revises: 314a9ea5a5e3
Create Date: 2026-09-11 20:25:40.167991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d3248dcc984'
down_revision: Union[str, Sequence[str], None] = '314a9ea5a5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('participant_a_id', sa.UUID(), nullable=False),
    sa.Column('participant_b_id', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('a_last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('participant_a_id < participant_b_id', name='ck_conversation_ordered'),
    sa.ForeignKeyConstraint(['participant_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_a_id', 'participant_b_id', name='uq_conversation_pair')
    )
    op.create_index('ix_conversation_a', 'conversations', ['participant_a_id', 'last_message_at'], unique=False)
    op.create_index('ix_conversation_b', 'conversations', ['participant_b_id', 'last_message_at'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.add_column('helper_profiles', sa.Column('admin_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('services', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('services', sa.Column('show_in_nav', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('services', sa.Column('nav_label', sa.String(length=40), server_default='', nullable=False))
    op.add_column('users', sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_prefs')
    op.drop_column('services', 'nav_label')
    op.drop_column('services', 'show_in_nav')
    op.drop_column('services', 'is_active')
    op.drop_column('helper_profiles', 'admin_hidden')
    op.drop_index('ix_message_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversation_b', table_name='conversations')
    op.drop_index('ix_conversation_a', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
